#include "core/safetensors.hpp"

#include <cstdio>
#include <string>

#include "core/json.hpp"
#include "testing.hpp"

namespace {

/// Writes raw bytes to a scratch file under build/ and returns its path.
std::string write_scratch(const char* name, const std::string& bytes) {
    NANO_CHECK(std::system("mkdir -p build/test_scratch") == 0);
    const std::string path = std::string("build/test_scratch/") + name;
    std::FILE* f = std::fopen(path.c_str(), "wb");
    NANO_CHECK(f != nullptr);
    if (f != nullptr) {
        std::fwrite(bytes.data(), 1, bytes.size(), f);
        std::fclose(f);
    }
    return path;
}

}  // namespace

int main() {
    const std::string dir = nano::testing::require_model_dir();
    const std::string model_path = dir + "/model.safetensors";
    if (!nano::testing::file_exists(model_path)) {
        nano::testing::skip("model.safetensors not downloaded");
    }

    const nano::SafeTensors st(model_path);

    // Structure of the real checkpoint, cross-checked against
    // tests/data/embed_golden.json (generated by scripts/gen_golden.py with
    // numpy from the same file).
    const nano::json::Value golden =
        nano::json::parse(nano::json::read_file("tests/data/embed_golden.json"));

    NANO_CHECK(st.tensors().size() == static_cast<size_t>(golden.at("tensor_count").as_int()));
    NANO_CHECK(st.total_params() == golden.at("total_params").as_int());

    const nano::TensorInfo& embed = st.require("model.embed_tokens.weight");
    NANO_CHECK(embed.dtype == nano::DType::BF16);
    NANO_CHECK(embed.shape.size() == 2);
    NANO_CHECK(embed.shape[0] == 151936);
    NANO_CHECK(embed.shape[1] == 896);
    NANO_CHECK(embed.numel() == 151936 * 896);
    NANO_CHECK(st.raw(embed).size() == static_cast<size_t>(embed.numel()) * 2);

    // Every layer-0 weight the forward pass will need is present.
    for (const char* name : {
             "model.layers.0.self_attn.q_proj.weight",
             "model.layers.0.self_attn.k_proj.weight",
             "model.layers.0.self_attn.v_proj.weight",
             "model.layers.0.self_attn.o_proj.weight",
             "model.layers.0.mlp.gate_proj.weight",
             "model.layers.0.mlp.up_proj.weight",
             "model.layers.0.mlp.down_proj.weight",
             "model.layers.0.input_layernorm.weight",
             "model.layers.0.post_attention_layernorm.weight",
             "model.norm.weight",
         }) {
        NANO_CHECK_MSG(st.find(name) != nullptr, "missing tensor %s", name);
    }
    NANO_CHECK(st.find("no.such.tensor") == nullptr);
    NANO_CHECK_THROWS(st.require("no.such.tensor"));

    // bf16 -> fp32 widening is bit-exact vs the numpy golden values.
    {
        const std::vector<float> f32 = st.to_f32(embed);
        const auto& expected = golden.at("first_values_f32").items();
        NANO_CHECK(f32.size() == static_cast<size_t>(embed.numel()));
        for (size_t i = 0; i < expected.size(); ++i) {
            NANO_CHECK_MSG(static_cast<double>(f32[i]) == expected[i].as_double(),
                           "value %zu: got %.17g, want %.17g", i, static_cast<double>(f32[i]),
                           expected[i].as_double());
        }
    }

    // Malformed files are rejected with clear errors, never crashes.
    NANO_CHECK_THROWS(nano::SafeTensors("build/test_scratch/does_not_exist.safetensors"));
    NANO_CHECK_THROWS(nano::SafeTensors(write_scratch("tiny.st", "abc")));
    // Header length claims more bytes than the file has.
    NANO_CHECK_THROWS(nano::SafeTensors(
        write_scratch("overlong.st", std::string("\xFF\xFF\xFF\xFF\x00\x00\x00\x00", 8))));
    // Valid length prefix, garbage JSON.
    NANO_CHECK_THROWS(nano::SafeTensors(
        write_scratch("badjson.st", std::string("\x03\x00\x00\x00\x00\x00\x00\x00", 8) + "{{{")));
    // Well-formed JSON whose offsets run past the data section.
    {
        const std::string header =
            R"({"t": {"dtype": "F32", "shape": [4], "data_offsets": [0, 16]}})";
        std::string bytes(8, '\0');
        bytes[0] = static_cast<char>(header.size());
        bytes += header;
        bytes += std::string(8, '\0');  // only 8 data bytes; offsets claim 16
        NANO_CHECK_THROWS(nano::SafeTensors(write_scratch("oob.st", bytes)));
    }
    // Shape/offsets size mismatch.
    {
        const std::string header =
            R"({"t": {"dtype": "F32", "shape": [4], "data_offsets": [0, 8]}})";
        std::string bytes(8, '\0');
        bytes[0] = static_cast<char>(header.size());
        bytes += header;
        bytes += std::string(8, '\0');
        NANO_CHECK_THROWS(nano::SafeTensors(write_scratch("mismatch.st", bytes)));
    }

    return nano::testing::finish("test_safetensors");
}
